### ISSUE TITLE
Using the library

### ISSUE THREAD

**Issue by olamiko** [nickaleks/merkletree#1]
Hi, I am trying to use the Merkle Tree library but I am not able to instatiate the Merkle Tree class and the Serial hasher. Do you have any pointers? @nickaleks

**Comment by nickaleks** [comment]
Hello, could you please provide a code sample which does not work and output of the compiler.

**Comment by olamiko** [comment]
`
unique_ptr<Sha256Hasher> NewSha256Hasher() {
    return unique_ptr<Sha256Hasher>(new Sha256Hasher);
}

int main(){

    MerkleTree tree(NewSha256Hasher());
}`

That is the code and the trace is below

`/opt/clion-2018.1/bin/cmake/bin/cmake --build /home/oomolola/Documents/merkletree/cmake-build-debug --target main -- -j 2
Scanning dependencies of target main
[ 50%] Building CXX object CMakeFiles/main.dir/main.cc.o
[100%] Linking CXX executable main
CMakeFiles/main.dir/main.cc.o: In function NewSha256Hasher():
/home/oomolola/Documents/merkletree/main.cc:14: undefined reference to Sha256Hasher::Sha256Hasher()
CMakeFiles/main.dir/main.cc.o: In function main:
/home/oomolola/Documents/merkletree/main.cc:19: undefined reference to MerkleTree::MerkleTree(std::unique_ptr<SerialHasher, std::default_delete<SerialHasher> >)
/home/oomolola/Documents/merkletree/main.cc:19: undefined reference to MerkleTree::~MerkleTree()
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:94: recipe for target 'main' failed
make[3]: *** [main] Error 1
CMakeFiles/Makefile2:67: recipe for target CMakeFiles/main.dir/all failed
make[2]: *** [CMakeFiles/main.dir/all] Error 2
CMakeFiles/Makefile2:79: recipe for target CMakeFiles/main.dir/rule failed
make[1]: *** [CMakeFiles/main.dir/rule] Error 2
Makefile:118: recipe for target 'main' failed
make: *** [main] Error 2`

@nickaleks, please note that I am using the concrete hasher implementation from the CT project

**Comment by nickaleks** [comment]
Seems like cmake could not link the library, can you provide your project structure along with CMakeLists.txt file?

**Comment by olamiko** [comment]
Here is my CMakeLists.txt

`cmake_minimum_required(VERSION 3.0)

project(merkletree)

include(FeatureSummary)

SET(CMAKE_CXX_FLAGS "-std=c++1y -Wall")
SET(CMAKE_CXX_FLAGS_RELEASE "-O3")
SET(CMAKE_CXX_FLAGS_DEBUG   "-g -Wextra -O0 -fdiagnostics-color")
SET(CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake/Modules)

include_directories( ${MY_SOURCE_DIR}/merkletree)

add_executable(main main.cc)`

The project structure is:

Merkletree // This folder contains the merkletree includes folder and the concrete implementations
--merkletree // this folder contains the include files
--main.cc
--merkletree.cc 

I hope you understand the folder structure @nickaleks

**Comment by nickaleks** [comment]
Seems like you forgot to link the library to your executable

add target_include_libraries(main merkletree) after add_executable

**Comment by olamiko** [comment]
Hi, I made some changes and linked the necessary libraries but I still got this error.

`Scanning dependencies of target merkle
[ 25%] Building CXX object CMakeFiles/merkle.dir/serial_hasher.cc.o
[ 25%] Building CXX object CMakeFiles/merkle.dir/merkle_tree.cc.o
[ 37%] Building CXX object CMakeFiles/merkle.dir/tree_hasher.cc.o
[ 50%] Building CXX object CMakeFiles/merkle.dir/merkle_verifier.cc.o
[ 62%] Building CXX object CMakeFiles/merkle.dir/merkle_tree_math.cc.o
[ 75%] Linking CXX static library libmerkle.a
[ 75%] Built target merkle
Scanning dependencies of target main
make[3]: *** No rule to make target ssl-NOTFOUND, needed by main.  Stop.
CMakeFiles/Makefile2:104: recipe for target CMakeFiles/main.dir/all failed
make[2]: *** [CMakeFiles/main.dir/all] Error 2
CMakeFiles/Makefile2:116: recipe for target CMakeFiles/main.dir/rule failed
make[1]: *** [CMakeFiles/main.dir/rule] Error 2
Makefile:131: recipe for target 'main' failed
make: *** [main] Error 2`

Here is my CMAKE file

`cmake_minimum_required(VERSION 3.0)

project(merkletree)

include(FeatureSummary)

SET(CMAKE_CXX_FLAGS "-std=c++1y -Wall")
SET(CMAKE_CXX_FLAGS_RELEASE "-O3")
SET(CMAKE_CXX_FLAGS_DEBUG   "-g -Wextra -O0 -fdiagnostics-color")
SET(CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake/Modules)

include_directories( ${MY_SOURCE_DIR}/merkletree)

add_executable(main main.cc)

add_library(merkle merkle_tree.cc serial_hasher.cc tree_hasher.cc merkle_verifier.cc merkle_tree_math.cc)
add_library(ssl STATIC IMPORTED openssl/sha.h stddef.h memory string)

target_link_libraries(merkle ssl)
target_link_libraries(main merkle)`

@nickaleks I guess the main problem is this line  `** No rule to make target ssl-NOTFOUND, needed by main. Stop.` and I have no idea on how to solve it. I tried to adjust the linking but it did not work.

**Comment by nickaleks** [comment]
Have you tried putting add_library before add_executable?

**Comment by olamiko** [comment]
Yes I did that. It gave the same error

**Comment by nickaleks** [comment]
What if you do not use ssl target right now, will it build?

**Comment by olamiko** [comment]
It won't build because I need functions from the openssl library. This also prompted me to include all libraries

**Comment by nickaleks** [comment]
If you can, please provide your code in zip file, I will try to find the issue and fix it.

**Comment by olamiko** [comment]
I can, it is attached
[merkletree.zip](https://github.com/nickaleks/merkletree/files/1960502/merkletree.zip)

Thank you

**Comment by nickaleks** [comment]
Thank you, I will take a look at it

**Comment by olamiko** [comment]
Hi @nickaleks , have you had time to go through it?

**Comment by nickaleks** [comment]
I am sorry but I did not have time yet. I will look at it today or tomorrow.

**Comment by olamiko** [comment]
No problem @nickaleks , have you had time to check it now?

**Comment by nickaleks** [comment]
@olamiko Sorry I took a while. I was able to compile it. The issue was you were including openssl header, but not linking the library itself. Here is the correct way to link openssl to your project:
```
cmake_minimum_required(VERSION 3.0)

project(merkletree)

include(FeatureSummary)

SET(CMAKE_CXX_FLAGS "-std=c++1y -Wall")
SET(CMAKE_CXX_FLAGS_RELEASE "-O3")
SET(CMAKE_CXX_FLAGS_DEBUG   "-g -Wextra -O0 -fdiagnostics-color")
SET(CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake/Modules)

include_directories(${MY_SOURCE_DIR}/merkletree)

add_library(merkle merkle_tree.cc serial_hasher.cc tree_hasher.cc merkle_verifier.cc merkle_tree_math.cc)
find_package(OpenSSL REQUIRED)
include_directories(${OPENSSL_INCLUDE_DIR})

add_executable(main main.cc)

target_link_libraries(merkle ${OPENSSL_LIBRARIES})
target_link_libraries(main merkle)
```

You need openssl library of course, and run cmake like this:
```
cmake .. -DOPENSSL_ROOT_DIR=/path/to/openssl -DOPENSSL_INCLUDE_DIR=/path/to/openssl/includes/
```

For me on OS X with system-wide openssl it was:
```
cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include/
```

**Comment by olamiko** [comment]
Hi, thank you. It works. Thank you for the time. Now I can move ahead

**Comment by nickaleks** [comment]
You are welcome :)
